# Generated by Django 4.2.1 on 2023-06-05 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("commentary", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="parent_commentary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_commentaries",
                to="commentary.commentary",
            ),
        ),
    ]
