# Generated by Django 4.2.1 on 2023-06-07 09:09

import commentary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commentary", "0003_alter_commentary_parent_commentary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Commentaries",
            },
        ),
        migrations.AddField(
            model_name="commentary",
            name="uploads",
            field=models.FileField(
                null=True,
                upload_to=commentary.models.upload_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png", "gif", "txt"]
                    )
                ],
            ),
        ),
    ]
