# Generated by Django 4.2.1 on 2023-06-07 13:14

from django.core.management import call_command
from django.db import migrations


def func(apps, schema_editor):
    call_command("loaddata", "data_fixture.json")


class Migration(migrations.Migration):
    dependencies = [
        ("commentary", "0004_alter_commentary_options_commentary_uploads"),
    ]

    operations = [migrations.RunPython(func)]
